name: 'meta'
version: '1.0.0'
config-version: 2

profile: 'meta'

vars:
  bq_project: "tccmarketing"

models:
  meta:
    staging:
      +materialized: view
      +schema: staging

    transform:
      +materialized: table
      +schema: silver

    analytics:
      +materialized: table
      +schema: gold
