# profiles.yml

retail:
 target: dev
 outputs:
  dev:
    type: bigquery
    method: service-account
    keyfile: /usr/local/airflow/include/gcp/service_account.json
    project: tccmarketing
    dataset: meta
    threads: 1
    timeout_seconds: 300
    location: US